name: Deploy Functions to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repo
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0  
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  
        project_id: ${{ secrets.GCP_PROJECT_ID }}  

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    # Deploy all functions
    - name: Deploy image-dates function
      run: |
        gcloud functions deploy image-dates \
          --no-allow-unauthenticated \
          --entry-point=handler \
          --runtime=python312 \
          --trigger-http \
          --source=image-dates \
          --region=us-south1 \
          --gen2 \
          --memory=256MB \
          --timeout=60s \
          --max-instances=2 \
          --min-instances=0 \
          --concurrency=1

