name: Deploy Functions to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 'Deploy image-dates function'
        run: |
          gcloud functions deploy image-dates \
            --no-allow-unauthenticated \
            --entry-point=handler \
            --runtime=python312 \
            --trigger-http \
            --source=image-dates \
            --region=us-south1 \
            --gen2 \
            --memory=256MB \
            --timeout=60s \
            --max-instances=2 \
            --min-instances=0 \
            --concurrency=1
